---
version: '2.3'
services:
  db:
    image: "postgres:11.1-alpine"
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PAASWORD: password
      POSTGRES_DB: postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - private-network
    ports:
      - "5432:5432"
  web-app:
    build: ./web-app
    ports:
    - 8080:8080
    networks:
      - public-network
      - private-network
    depends_on:
      - db
      - redis

  test-app:
    build: ./test-app
    ports:
      - 8091:8091
    networks:
      - public-network
  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - private-network


volumes:
  db-data:

networks:
  public-network:
  private-network:
